Add openapi.yaml to the repository.
octobox/octobox pull request #3633
Opened 2024-03-02 17:49 UTC by rickwysocki

I created an openapi.yaml spec file for Octobox. I relied both on [existing documentation](https://octobox.io/docs/) and my own testing of the endpoints in a Docker version of the application. I have a points/questions to review:

- I don't think I was able to get the sync/syncing endpoints, in the notifications controller, to work in my testing. Sync (/api/notifications/sync.json) might have worked since, based on the existing documentation, there wouldn't be a response, but I couldn't find any evidence of it working. Syncing (/api/notifications/syncing.json) only ever returned full HTML pages in Terminal. I may have misinterpreted elements of the existing documentation here.
- I couldn't seem to post or patch pinned searches. Both returned HTML pages in Terminal. Additionally, the response examples in the existing documentation confused me, so I don't think the responses are currently correct. I'd love to work more on this if you have any thoughts.
- I've left a few other in-text comments for smaller points, such as info I wasn't sure of or didn't have.

This was a lot of fun! I'd love to keep working on this with your feedback on the current version.

2024-03-03 19:51 UTC, andrew commented
Looking good, thanks for tackling this, I've just merged an update that fixes running octobox via docker-compose, so that may solve some of the issues you were running into.

2024-03-03 21:32 UTC, rickwysocki commented
Thanks for the update! I verified that Swagger's curl command works for `api/notifications/sync.json`, but I'm still getting responses of very large HTML/Ruby files when using the commands produced for syncing, posting pinned searches, and updating pinned searches. There don't seem to be any changes made to the local version of Octobox I'm running using Docker, either. I'll take another look tomorrow, but any advice would be helpful. 

I'm happy to work on this as long as is useful, by the way, as I'm trying to get my API documentation chops together.

2024-03-03 22:07 UTC, andrew commented
It could well be broken, although all the tests are passing which makes me think it’s a config issue, I’ll also give them a try tomorrow. 

This is really helpful, thanks for contributing

2024-03-06 21:18 UTC, rickwysocki commented
Hi there: Just an update that I tried those commands using my live Octobox URL rather than Docker. While this didn't return HTML in terminal, I still wasn't able to post or patch pinned notifications using CURL. Additionally, I'm also still not sure whether syncing feature is working or not.

2024-03-14 17:13 UTC, rickwysocki commented
Hi there! Just following up to ask if you'd had a chance to look at those endpoints and/or any instructions for to continuing working on the API documentation.

2024-03-14 18:12 UTC, andrew commented
Sorry for the delay, I’ll review this later tonight

2024-03-14 21:23 UTC, andrew requested changes

2024-03-14 21:23 UTC, andrew commented on openapi.yaml
> +    post: # I couldn't get this to work using CURL. Maybe it's because I'm using Docker/doing local testing? The JSON in the current documentation was throwing me a bit, too, and I had a hard time va
I was able to get this to work locally with curl: 
```
curl -X POST -d "pinned_search[query]=foo" -d "pinned_search[name]=bar" -H "Authorization: Bearer MYTOKEN" http://localhost:3000/api/pinned_searches.json
{"id":4,"user_id":1,"query":"inbox:true foo","name":"bar","count":6,"created_at":"2024-03-14T21:16:48.433Z","updated_at":"2024-03-14T21:16:48.433Z"}
```

2024-03-14 21:23 UTC, andrew commented on openapi.yaml
> +    patch: # I couldn't get this to work using CURL. Maybe it's because I'm using Docker/doing local testing? The JSON in the current documentation was throwing me a bit, too, and I had a hard time v
I managed to get it working locally with curl: 
```
curl -X PATCH -d "pinned_search[query]=foobar" -d "pinned_search[name]=baz" -H "Authorization: Bearer MYTOKEN" http://localhost:3000/api/pinned_searches/4.json
```

2024-03-14 21:24 UTC, andrew commented on openapi.yaml
> +    profile:
```suggestion
    User:
```

2024-03-14 21:25 UTC, andrew commented on openapi.yaml
> +    patch-response:
Can we rename this to something like "Refresh setting"

2024-03-14 21:28 UTC, andrew commented on openapi.yaml
> +            type: object
Can we pull this object out into it's own `Notification` Object and do:

```
items:
  "$ref": "#/components/schemas/Notification"
```

here instead

2024-03-14 21:29 UTC, andrew commented on openapi.yaml
> +          type: object
Can we pull this out into it's own `Subject` object and reference it here

2024-03-14 21:29 UTC, andrew commented on openapi.yaml
> +        repo:
Can we pull this out into it's own `Repo` object and reference it here

2024-03-14 21:33 UTC, andrew commented
I've added some inline comments, it's looking good so far, the schemas could do with a bit of tweaking to seperate the different objects and use the `$ref` feature of openapi.

Example: https://github.com/ecosyste-ms/packages/blob/main/openapi/api/v1/openapi.yaml#L1103

I could get all of the api endpoints working, a couple return 200 instead of 204, the creating and updating of pinned searches is a bit confusing as it follows the rails convention for parameters, I left examples in the comments above.

2024-03-14 21:34 UTC, andrew commented
I also opened up the file in https://editor.swagger.io, all working and no errors!

![Screenshot 2024-03-14 at 21-33-44 Swagger Editor](https://github.com/octobox/octobox/assets/1060/646d045d-e57b-4ba0-8eaf-2f8e2aea9d7f)

2024-03-15 11:45 UTC, Gerard19742608jourdain commented
simply space

2024-03-16 17:46 UTC, rickwysocki commented
Thanks for this feedback! It's really helpful on my end. I'll start working on your recommendations and check in once I've finished the revisions.

2024-03-23 14:57 UTC, rickwysocki commented
I've made some revisions to the `openapi.yaml` file based on your helpful recommendations. The only things I still seem to have issues with are the two sync-related endpoints. 

1. For the `api/notifications/sync.json` endpoint, I get a 200 response with no body in Swagger. In Terminal, I seem to be getting a 400 error when I run a verbose CURL request produced by Swagger.
2. For the `api/notifications/syncing.json` endpoint, I get a 200 response in both Swagger and Terminal, but it comes with an `"error": null`.

I've attached screenshots showing those errors on my end. Everything else seems to be working for me, and I've made your requested changes. 

------------

<img width="701" alt="image" src="https://github.com/octobox/octobox/assets/16529152/6e505bcf-a96e-4677-8470-412c78a507ad">

------------

<img width="753" alt="image" src="https://github.com/octobox/octobox/assets/16529152/a941126e-b4a3-41e2-ba62-a7eccd1bdf2c">

2024-04-09 19:52 UTC, rickwysocki commented
Hi there: Just touching base to see whether there is more work I can do on this. No rush on my end!

2024-04-12 09:29 UTC, andrew commented
@rickwysocki nothing more needed from your right now, I'm travelling for work at the moment, hope to get back to this in about a week

2025-08-01 07:17 UTC, merged

2025-08-01 07:18 UTC, andrew commented
Sorry for the delay @rickwysocki, I've merged this now, thanks for your work on it.

2025-08-01 07:34 UTC, andrew commented
Added a link to it in the readme: https://github.com/octobox/octobox/tree/master?tab=readme-ov-file#api-documentation